POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "bharadwaj_vemparala",
    "name": "Bharadwaj",
    "password": "Invincible@303",
    "gender": "Male"
}
###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "aditya_ammu",
    "password": "Invincible@303"
}
###

GET http://localhost:3000/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZGl0eWFfYW1tdSIsIm5hbWUiOiJBZGl0eWEiLCJnZW5kZXIiOiJNYWxlIiwiaWF0IjoxNzQ0NTUxMzYyfQ.mIHfhGm983QkgTHoWXZz7cnit3xWQfmuYmdDa0_AEMk
###

POST http://localhost:3000/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZGl0eWFfYW1tdSIsIm5hbWUiOiJBZGl0eWEiLCJnZW5kZXIiOiJNYWxlIiwiaWF0IjoxNzQ0NTUxMzYyfQ.mIHfhGm983QkgTHoWXZz7cnit3xWQfmuYmdDa0_AEMk

{
    "categoryName": "Cotton Clothes",
    "itemCount": 150,
    "categoryImage": "https://res.cloudinary.com/dtrjr55q7/image/upload/v1744823889/portrait-handsome-young-man_feul9k.jpg"
}
###

PUT http://localhost:3000/categories/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZGl0eWFfYW1tdSIsIm5hbWUiOiJBZGl0eWEiLCJnZW5kZXIiOiJNYWxlIiwiaWF0IjoxNzQ0NTUxMzYyfQ.mIHfhGm983QkgTHoWXZz7cnit3xWQfmuYmdDa0_AEMk

{
    "categoryName": "Mens Clothes"
}
###